import type { PathProject } from "@/lib/path/types";

/** Curated native projects — in-app checklist is the product, not outbound tutorials. */
export const PATH_PROJECTS: PathProject[] = [
  {
    slug: "url-shortener",
    title: "URL Shortener API",
    difficulty: "beginner",
    time_hours: [8, 14],
    languages: ["TypeScript"],
    stack: ["Next.js", "Postgres", "REST"],
    domain: "Backend & APIs",
    what_you_build: [
      "POST /shorten that returns a short code for a long URL",
      "GET /:code that 302-redirects to the original URL",
      "Click counts and a tiny admin list of your links",
    ],
    what_it_teaches: [
      "Designing a clean REST surface with validation",
      "Idempotent writes and unique constraints",
      "Redirect semantics and basic analytics",
    ],
    how_it_works: [
      {
        step: 1,
        title: "Model the link",
        detail: "Store original_url, short_code, created_at, click_count. Generate codes that are URL-safe and unique.",
      },
      {
        step: 2,
        title: "Shorten endpoint",
        detail: "Validate URL, insert row, return the public short URL. Reject duplicates or reuse codes intentionally.",
      },
      {
        step: 3,
        title: "Redirect path",
        detail: "Lookup by code, increment clicks, redirect. Return 404 for unknown codes — never leak internals.",
      },
      {
        step: 4,
        title: "Show your work",
        detail: "A minimal page lists your links with click counts so you can demo the loop end-to-end.",
      },
    ],
    build_checklist: [
      { id: "schema", title: "Create links table with unique short_code" },
      { id: "shorten", title: "Implement POST /api/shorten with URL validation" },
      { id: "redirect", title: "Implement GET /r/[code] redirect + click increment" },
      { id: "list", title: "Build a simple list UI of created links" },
      { id: "errors", title: "Handle invalid URLs and missing codes cleanly" },
      { id: "readme", title: "Write a 5-bullet README: problem, API, schema, tradeoffs", optional: true },
    ],
    take_it_further: ["Rate-limit shorten by IP", "Custom aliases", "Expiration dates"],
    interview_roi: "Shows you can ship a real API with persistence, redirects, and measurable usage — classic internship backend signal.",
    fits_stages: ["foundations", "http-apis", "ship-first-project"],
    target_role_tags: ["swe-intern", "backend-intern", "fullstack-intern"],
  },
  {
    slug: "habit-tracker",
    title: "Habit Tracker",
    difficulty: "beginner",
    time_hours: [10, 16],
    languages: ["TypeScript"],
    stack: ["Next.js", "Postgres", "Auth"],
    domain: "Full-stack Web",
    what_you_build: [
      "Auth-gated habit list with daily checkmarks",
      "Streak calculation that survives timezone edges",
      "A week grid that makes progress obvious",
    ],
    what_it_teaches: [
      "CRUD with ownership (RLS or equivalent)",
      "Date math without off-by-one bugs",
      "UI state that mirrors server truth",
    ],
    how_it_works: [
      {
        step: 1,
        title: "Own the data",
        detail: "Habits belong to a user. Completions are (habit_id, date). Never trust client user ids blindly.",
      },
      {
        step: 2,
        title: "Toggle a day",
        detail: "Checking a box inserts a completion; unchecking deletes it. Idempotent toggles beat racey counters.",
      },
      {
        step: 3,
        title: "Compute streaks",
        detail: "Count consecutive days ending today (or yesterday if not yet checked). Document the rule you chose.",
      },
      {
        step: 4,
        title: "Render the week",
        detail: "Show the last 7 days per habit. Empty states matter as much as filled ones.",
      },
    ],
    build_checklist: [
      { id: "auth", title: "Gate the app behind sign-in" },
      { id: "habits-crud", title: "Create / rename / archive habits for the current user" },
      { id: "toggle", title: "Toggle completion for a calendar day" },
      { id: "streak", title: "Display current streak with a clear date rule" },
      { id: "week-grid", title: "Render a 7-day completion grid" },
      { id: "empty", title: "Empty state that prompts creating the first habit", optional: true },
    ],
    interview_roi: "Proves full-stack ownership: auth, per-user data, and a productized daily loop interviewers can click through.",
    fits_stages: ["foundations", "ship-first-project", "polish-and-deploy"],
    target_role_tags: ["swe-intern", "fullstack-intern", "frontend-intern"],
  },
  {
    slug: "spaced-flashcards",
    title: "Spaced Repetition Flashcards",
    difficulty: "intermediate",
    time_hours: [12, 20],
    languages: ["TypeScript"],
    stack: ["Next.js", "Postgres"],
    domain: "Product Logic",
    what_you_build: [
      "Decks and cards with front/back",
      "A study session that schedules next review",
      "Due-today queue that shrinks as you answer",
    ],
    what_it_teaches: [
      "Modeling recurring work with next_review_at",
      "Simple SM-2-ish or Leitner scheduling",
      "Session UX that feels fast under keyboard",
    ],
    how_it_works: [
      {
        step: 1,
        title: "Card model",
        detail: "Store front, back, ease/interval, next_review_at. New cards are due immediately.",
      },
      {
        step: 2,
        title: "Study queue",
        detail: "Fetch cards where next_review_at <= now, ordered by due date. Cap session size.",
      },
      {
        step: 3,
        title: "Grade answers",
        detail: "Again / Good / Easy updates interval and next_review_at. Persist after each grade.",
      },
      {
        step: 4,
        title: "Deck home",
        detail: "Show due count per deck so the user knows what to study next.",
      },
    ],
    build_checklist: [
      { id: "decks", title: "CRUD decks owned by the user" },
      { id: "cards", title: "Add/edit/delete cards in a deck" },
      { id: "queue", title: "Build due-today study queue" },
      { id: "grade", title: "Implement Again/Good/Easy scheduling update" },
      { id: "keyboard", title: "Space to flip, 1/2/3 to grade", optional: true },
      { id: "stats", title: "Show due count and reviewed-today count" },
    ],
    interview_roi: "Signals algorithmic product thinking — you can explain scheduling tradeoffs without a LeetCode costume.",
    fits_stages: ["http-apis", "data-modeling", "ship-first-project"],
    target_role_tags: ["swe-intern", "fullstack-intern"],
  },
  {
    slug: "internship-portfolio",
    title: "Internship Portfolio Site",
    difficulty: "beginner",
    time_hours: [6, 12],
    languages: ["TypeScript"],
    stack: ["Next.js", "MDX or Markdown"],
    domain: "Frontend & Personal Brand",
    what_you_build: [
      "A one-page portfolio with projects, skills, and contact",
      "Project case studies with problem → approach → result",
      "Deployed URL you can paste into applications",
    ],
    what_it_teaches: [
      "Clear information hierarchy for recruiters",
      "Writing case studies that survive resume screens",
      "Shipping and owning a public URL",
    ],
    how_it_works: [
      {
        step: 1,
        title: "Structure the page",
        detail: "Hero with role target, projects, experience, contact. One scroll, no mystery navigation.",
      },
      {
        step: 2,
        title: "Case study template",
        detail: "Each project: problem, what you built, stack, one screenshot or GIF, link to repo/demo.",
      },
      {
        step: 3,
        title: "Make it yours",
        detail: "Replace lorem with real work — even class projects with honest scope.",
      },
      {
        step: 4,
        title: "Ship it",
        detail: "Deploy and verify mobile. The live URL is the deliverable.",
      },
    ],
    build_checklist: [
      { id: "layout", title: "Build hero + projects + contact sections" },
      { id: "case-study", title: "Write 2–3 project case studies with outcomes" },
      { id: "responsive", title: "Verify layout on a phone-width viewport" },
      { id: "deploy", title: "Deploy and confirm the public URL loads" },
      { id: "a11y", title: "Keyboard focus + alt text on images", optional: true },
    ],
    take_it_further: ["Dark mode toggle", "Blog index for writeups"],
    interview_roi: "Gives recruiters a clickable proof of taste and shipping — often the difference between resume pass and skip.",
    fits_stages: ["foundations", "polish-and-deploy", "apply-early"],
    target_role_tags: ["swe-intern", "frontend-intern", "fullstack-intern"],
  },
  {
    slug: "expense-splitter",
    title: "Expense Splitter",
    difficulty: "intermediate",
    time_hours: [12, 18],
    languages: ["TypeScript"],
    stack: ["Next.js", "Postgres"],
    domain: "Backend & APIs",
    what_you_build: [
      "Groups with members and shared expenses",
      "Balances that show who owes whom",
      "Settle-up suggestions that minimize transfers",
    ],
    what_it_teaches: [
      "Multi-entity modeling (groups, members, expenses, shares)",
      "Derived balances vs stored aggregates",
      "Explaining money math in interviews",
    ],
    how_it_works: [
      {
        step: 1,
        title: "Model the group",
        detail: "Groups have members. Expenses have payer, amount, and equal or custom splits.",
      },
      {
        step: 2,
        title: "Compute balances",
        detail: "Net each member: paid − owed. Positive means they should receive money.",
      },
      {
        step: 3,
        title: "Settle suggestions",
        detail: "Greedy match debtors to creditors. Document that exact cents may need rounding rules.",
      },
      {
        step: 4,
        title: "UI for trust",
        detail: "Show the ledger and the suggested transfers. Humans must be able to audit the math.",
      },
    ],
    build_checklist: [
      { id: "groups", title: "Create group + add members" },
      { id: "expense", title: "Add expense with equal split among members" },
      { id: "balances", title: "Compute and display per-member balances" },
      { id: "settle", title: "Suggest transfers that zero balances" },
      { id: "custom-split", title: "Support custom share percentages", optional: true },
      { id: "tests", title: "Unit-test balance math on 3 fixture groups" },
    ],
    interview_roi: "Lets you walk through data modeling and correctness under money constraints — strong systems intuition signal.",
    fits_stages: ["data-modeling", "http-apis", "ship-first-project"],
    target_role_tags: ["swe-intern", "backend-intern"],
  },
  {
    slug: "markdown-notes",
    title: "Markdown Notes App",
    difficulty: "beginner",
    time_hours: [8, 14],
    languages: ["TypeScript"],
    stack: ["Next.js", "Postgres"],
    domain: "Full-stack Web",
    what_you_build: [
      "Notes list with create/edit/delete",
      "Live Markdown preview beside the editor",
      "Search by title/body for your own notes",
    ],
    what_it_teaches: [
      "Optimistic vs confirmed save patterns",
      "Safe Markdown rendering",
      "Basic full-text or ILIKE search",
    ],
    how_it_works: [
      {
        step: 1,
        title: "CRUD notes",
        detail: "Title + body_md owned by user. Autosave on debounce or explicit Save — pick one and stick to it.",
      },
      {
        step: 2,
        title: "Preview pane",
        detail: "Render Markdown to HTML with a sanitizer. Never dangerouslySetInnerHTML raw user HTML.",
      },
      {
        step: 3,
        title: "Find notes",
        detail: "Search filters the list. Empty query shows recent notes.",
      },
    ],
    build_checklist: [
      { id: "crud", title: "Create, edit, delete notes for the signed-in user" },
      { id: "preview", title: "Side-by-side Markdown preview with sanitization" },
      { id: "search", title: "Filter notes by title/body query" },
      { id: "save-ux", title: "Clear saved/unsaved indicator" },
      { id: "keyboard", title: "Cmd/Ctrl+S to save", optional: true },
    ],
    interview_roi: "A familiar product you can demo quickly while talking about XSS, ownership, and editor UX tradeoffs.",
    fits_stages: ["foundations", "ship-first-project", "polish-and-deploy"],
    target_role_tags: ["swe-intern", "frontend-intern", "fullstack-intern"],
  },
  {
    slug: "realtime-chat-rooms",
    title: "Realtime Chat Rooms",
    difficulty: "intermediate",
    time_hours: [14, 22],
    languages: ["TypeScript"],
    stack: ["Next.js", "Postgres", "Realtime"],
    domain: "Realtime Systems",
    what_you_build: [
      "Named rooms with membership",
      "Message list that updates live for participants",
      "Basic presence or “typing” optional polish",
    ],
    what_it_teaches: [
      "Event-driven UI updates",
      "Ordering and pagination for chat",
      "Authz: who can read/write a room",
    ],
    how_it_works: [
      {
        step: 1,
        title: "Rooms + members",
        detail: "Users join rooms. Messages reference room_id and author_id.",
      },
      {
        step: 2,
        title: "Send + list",
        detail: "Insert message, return newest page. Load older messages on scroll-up.",
      },
      {
        step: 3,
        title: "Subscribe",
        detail: "Listen for inserts on the room channel and append if not already present.",
      },
      {
        step: 4,
        title: "Guard rails",
        detail: "Trim length, rate-limit sends, reject non-members.",
      },
    ],
    build_checklist: [
      { id: "rooms", title: "Create/join rooms with membership rows" },
      { id: "messages", title: "Post messages and list recent history" },
      { id: "live", title: "Subscribe so new messages appear without refresh" },
      { id: "authz", title: "Block read/write for non-members" },
      { id: "pagination", title: "Load older messages", optional: true },
      { id: "typing", title: "Typing indicator", optional: true },
    ],
    interview_roi: "Gives you a concrete story for websockets/realtime, fanout, and authorization — frequent internship deep-dive topics.",
    fits_stages: ["http-apis", "data-modeling", "systems-lite"],
    target_role_tags: ["swe-intern", "backend-intern", "fullstack-intern"],
  },
  {
    slug: "job-listings-board",
    title: "Mini Job Listings Board",
    difficulty: "intermediate",
    time_hours: [12, 20],
    languages: ["TypeScript"],
    stack: ["Next.js", "Postgres"],
    domain: "Full-stack Web",
    what_you_build: [
      "Seeded or admin-added job listings",
      "Filters for kind, location, and keyword",
      "Saved jobs for the signed-in user",
    ],
    what_it_teaches: [
      "Filter query design that stays index-friendly",
      "Bookmarking with a join table",
      "Empty and loading states recruiters notice",
    ],
    how_it_works: [
      {
        step: 1,
        title: "Listing model",
        detail: "title, org, kind, locations, url, posted_at. Seed 20 realistic rows.",
      },
      {
        step: 2,
        title: "Filter bar",
        detail: "Compose WHERE clauses from search params. Reset clears to defaults.",
      },
      {
        step: 3,
        title: "Save jobs",
        detail: "user_saved_jobs(user_id, job_id). Toggle from the list without full reload.",
      },
      {
        step: 4,
        title: "Saved view",
        detail: "A /saved-jobs style tab shows only bookmarked listings.",
      },
    ],
    build_checklist: [
      { id: "seed", title: "Seed ≥20 listings with varied orgs/kinds" },
      { id: "list", title: "Paginated listings page with filters" },
      { id: "save", title: "Toggle save/unsave for current user" },
      { id: "saved-tab", title: "View only saved listings" },
      { id: "detail", title: "Detail page with apply link", optional: true },
    ],
    interview_roi: "Mirrors product surfaces you’ll build as an intern and lets you discuss filtering, pagination, and personalization.",
    fits_stages: ["http-apis", "ship-first-project", "apply-early"],
    target_role_tags: ["swe-intern", "fullstack-intern", "frontend-intern"],
  },
  {
    slug: "rate-limit-playground",
    title: "Rate Limit Playground",
    difficulty: "advanced",
    time_hours: [10, 16],
    languages: ["TypeScript"],
    stack: ["Next.js", "Redis or in-memory"],
    domain: "Backend & APIs",
    what_you_build: [
      "An API endpoint protected by token-bucket or fixed-window limiting",
      "A demo UI that fires bursts and shows 429s",
      "Headers that expose limit/remaining/reset",
    ],
    what_it_teaches: [
      "Choosing a rate-limit algorithm and naming its failure modes",
      "Idempotent client retries vs spam",
      "Observability for abuse controls",
    ],
    how_it_works: [
      {
        step: 1,
        title: "Pick an algorithm",
        detail: "Fixed window is simplest; token bucket is smoother. Implement one well.",
      },
      {
        step: 2,
        title: "Key by identity",
        detail: "Limit by IP or API key. Document multi-instance caveats if using memory.",
      },
      {
        step: 3,
        title: "Return 429",
        detail: "Include Retry-After or X-RateLimit-* headers. Body explains the limit.",
      },
      {
        step: 4,
        title: "Demo harness",
        detail: "Button that fires N parallel requests so you can show the limiter live.",
      },
    ],
    build_checklist: [
      { id: "limiter", title: "Implement limiter with configurable burst/window" },
      { id: "endpoint", title: "Protect a sample GET/POST with the limiter" },
      { id: "headers", title: "Emit remaining/reset headers on success and 429" },
      { id: "demo", title: "UI that bursts requests and shows responses" },
      { id: "tests", title: "Tests for under-limit and over-limit paths" },
      { id: "docs", title: "Document algorithm choice and multi-instance notes", optional: true },
    ],
    take_it_further: ["Per-user vs per-IP tiers", "Sliding window log"],
    interview_roi: "Hands you a crisp systems answer for abuse protection — interviewers love a demo over pure theory.",
    fits_stages: ["systems-lite", "http-apis"],
    target_role_tags: ["swe-intern", "backend-intern"],
  },
];

export function getProjectBySlug(slug: string): PathProject | undefined {
  return PATH_PROJECTS.find((p) => p.slug === slug);
}

export function listProjectSlugs(): string[] {
  return PATH_PROJECTS.map((p) => p.slug);
}
